server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?serverTimezone=Asia/Seoul
    username: cos
    password: cos1234

  jpa:
    hibernate:
      ddl-auto: update #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 858159507303-ruvunomi3hsm8dsk6ojh84gvlp8sprrn.apps.googleusercontent.com
            client-secret: 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
            scope:
            - email
            - profile
            
          facebook:
            client-id: 790877495636529
            client-secret: 7d653bcc498fcd9f7be31bcf3a024260
            scope:
            - email
            - public_profile
           